### ISSUE TITLE
PHP filesize() with 32 bit integers.

### ISSUE THREAD

**Issue by SushiDude** [lrsjng/h5ai#547]
This is a catch-all for issues related to:
https://secure.php.net/manual/en/function.filesize.php
> Note: Because PHP's integer type is signed and many platforms use 32bit integers, some filesystem functions may return unexpected results for files which are larger than 2GB.

---

As of h5ai version 0.28.1, the behavior causes **massive** performance issues and is wildly incorrect.

The problematic function being https://github.com/lrsjng/h5ai/blob/v0.28.1/src/_h5ai/private/php/core/class-filesize.php#L11 called by https://github.com/lrsjng/h5ai/blob/v0.28.1/src/_h5ai/private/php/core/class-util.php#L97.

I have tried many of the functions posted on the PHP Manual and Stack Overflow; none of them worked well. [BigFileTools](https://github.com/jkuchar/BigFileTools) does not support UTF-8, so it is a no-go.

There are three good options at this point:
1. Use an arbitrary precision library.
2. Use an external utility and display the size string it returns.
3. Use filesize() with no fallback for 32 bit integers.

Given the current issues, it would seem best to release a new version of h5ai with option three right now and consider making one or two a configurable option in the future.

---

This tracks the actual status of related issues:
- [ ] #524: Filesize optional
- [ ] #459: Getting network problem on my local PC ?
- [ ] #456: Files larger than 2GB on 32-bit compiled PHP
- [ ] #445: Function filesize bug
- [ ] #415: 502 caused by large file
- [ ] #322: filesize is wrong on 32bit system (armv5, mipsel, x86 etc)
- [ ] #162: Wrong / No Filesize with large files (32bit systems)
- [x] #114: filesize and filemtime warnings (files >2GB @ 32bit OS)

**Comment by lrsjng** [comment]
hey, thanks for summing it up.. currently I've removed any workaround code, and kind of added 64-bit PHP as a requirement (32-bit compiled PHP will get a red lamp on the info page, nothing more). Since PHP 5.5 there is a 64-bit version for Windows too, so anyone concerned about large file size should be able to set up the server this server..

**Comment by phiresky** [comment]
> should be able to set up the server this way..

As a counter point, I'm running h5ai on an ARMv7 NAS (32bit), and this issue is fairly annoying.

**Comment by phiresky** [comment]
I didn't read all the related issues, but what is the problem with something like this?
```php
if(PHP_INT_SIZE == 4) {
    if (strtoupper(substr(PHP_OS, 0, 3)) == 'WIN') {
        $size = trim(exec("for %F in (\"" . $file . "\") do @echo %~zF"));
    }
    elseif ((PHP_OS == 'Linux') || (PHP_OS == 'FreeBSD') || (PHP_OS == 'Unix') || (PHP_OS == 'SunOS')) {
        $size = trim(shell_exec("stat -c%s " . escapeshellarg($file)));
    } else {
        $size = filesize($file);
    }
}
```

**Comment by CreativForm** [comment]
I had find one hacky solution explained here: https://stackoverflow.com/a/48363570/2592415
